services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: testtask
      POSTGRES_USER: baseuser
      POSTGRES_PASSWORD: basepassword
    ports:
      - "5434:5432"  # Проксирую на другой порт, чтобы не конфликтовал с локальным сервером
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - net

  gateway:
    build:
      dockerfile: services/gateway/Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - broker
      - message_saver
    networks:
      - net

  message_saver:
    build:
      dockerfile: services/message_saver/Dockerfile
      context: .
    restart: unless-stopped
    depends_on:
      - broker
      - db
    networks:
      - net

  broker:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    networks:
      - net

networks:
  net:
    driver: bridge